# -*- mode: ruby -*-
# vi: set ft=ruby :

## раскоментируйте если вам не доступен ванльный репозиторий vagrant
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
## конфиг стенда
Vagrant.configure("2") do |config|

    machine_resources = {
        "WebServer" => {
            "cpus" => 2,
            "memory" => "1024",
            "ip" => "192.168.250.10"
        },
        "Client" => {
            "cpus" => 2,
            "memory" => "2048",
            "ip" => "192.168.250.20"
        }
    }

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.boot_timeout = 800
    config.vm.box_download_insecure=true
    config.vm.box = "ubuntu/jammy64"
    config.vm.disk :disk, size: "20GB", primary: true
    config.vm.provision "shell", path: "docker.sh"

    machine_resources.each do |name, resources|
        config.vm.define name do |config|  # устанавливаем имя для вм в vagrant
            config.vm.hostname = name
            config.vm.network "private_network", ip: resources["ip"]
            config.vm.synced_folder "./"+name, "/opt"

            config.vm.provider "virtualbox" do |server|
                server.name = name  # устанавливаем имя для вм в virtualbox
                server.cpus = resources["cpus"]
                server.memory = resources["memory"]
            end
        end
    end
end